# runner that works : #3 (VBcp8xyw) Boursouflet alias "CREMI"

stages:
  - format-check
  - coverage-check
  - testGNU_Linux

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "-B -ntp -f agon/pom.xml"
  JDK_IMAGE: "mcr.microsoft.com/java/jdk:21-ga"  # Microsoft OpenJDK 21 (projet constraint)

cache:
  key: maven-cache
  paths:
    - .m2/repository

default:
  image: $JDK_IMAGE
  tags:
    - Boursouflet
  before_script:
    - java -version
    - mvn -version

# same Template to all jobs
.test_java:
  tags:
    - Boursouflet
  before_script:
    - set -e
    - java -version
    - mvn -version
    # télécharge les dépendances si absentes dans le cache
    - mvn $MAVEN_CLI_OPTS -q -DskipTests dependency:go-offline || true
  script:
    - mvn test

# Template for all java jobs (avec Microsoft OpenJDK)
.java_template:
  tags:
    - Boursouflet
  image: $JDK_IMAGE  # use variable
  before_script:
    - set -e
    - java -version
    - mvn -version

# template for linux distrib' by default
.linux_test_template:
  tags:
    - Boursouflet
  before_script:
    - set -e
    - |
      if command -v apt-get > /dev/null; then
        apt-get update
        apt-get install -y 

# Tests on each distributions
check-format:
  stage: format-check
  image: $JDK_IMAGE
  tags:
    - Boursouflet
  script:
    - mvn spotless:check || (echo "Le code n'est pas correctement formaté. Voici les corrections nécessaires :"; mvn spotless:apply --dry-run)
  allow_failure: true

jacoco85p:
  extends: .test_java
  stage: coverage-check
  script:
    - mvn test jacoco:report
    - mvn jacoco:check
  allow_failure: true

test-debian:
  extends: .test_java
  stage: testGNU_Linux
  image: debian:bookworm

test-temurin:
  extends: .test_java
  stage: testGNU_Linux
  image: eclipse-temurin:21-jdk

test-alpine:
  extends: .test_java
  stage: testGNU_Linux
  image: alpine:3.19

test-fedora:
  extends: .test_java
  stage: testGNU_Linux
  image: fedora:39

# https://gitlab.archlinux.org/archbot
# https://gitlab.archlinux.org/archlinux/archlinux-docker/-/jobs?kind=BUILD
test-arch:
  extends: .test_java
  stage: testGNU_Linux
  image: archlinux:base-20260201.0.486523

test-ubuntu24:
  extends: .test_java
  stage: testGNU_Linux
  image: ubuntu:24.04

test-ubuntu22:
  extends: .test_java
  stage: testGNU_Linux
  image: ubuntu:22.04

test-opensuse:
  extends: .test_java
  stage: testGNU_Linux
  image: opensuse/leap:15.5

# end page
