package fr.univ.bordeaux.agoncore.history;

import fr.univ.bordeaux.agoncore.agonelements.Color;
import fr.univ.bordeaux.agoncore.agonelements.Move;
import fr.univ.bordeaux.agoncore.agonelements.PieceType;
import fr.univ.bordeaux.agoncore.bitboard.CoordinateMapper;
import fr.univ.bordeaux.technical.utils.GameLogger;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Stack;

/**
 * Manages the history of turns to support undo and redo operations.
 *
 * <p>This class maintains two stacks of {@link HistoryInformations}: * *
 *
 * <ul>
 *   <li><b>Undo Stack:</b> Stores the history of moves already played.
 *   <li><b>Redo Stack:</b> Stores moves that were undone and are available to be re-applied.
 * </ul>
 *
 * <p>*
 *
 * <p>Following standard command patterns, the redo stack is cleared whenever a new, original move
 * is added to the history to prevent branching timelines.
 */
public class History {

  /** Stack containing turns that can be reverted. */
  private final Stack<HistoryInformations> undoStack = new Stack<>();

  /** Stack containing turns that were reverted and can be re-applied. */
  private final Stack<HistoryInformations> redoStack = new Stack<>();

  private final Map<String, Integer> configurationCounts = new HashMap<>();
  // On garde aussi une pile des signatures pour pouvoir les décrémenter lors d'un undo
  private final Stack<String> signatureStack = new Stack<>();
  private final Stack<String> redoSignatureStack = new Stack<>();

  /** Initializes an empty game history. */
  public History() {
    GameLogger.debug("History: New empty history initialized.");
  }

  /**
   * Reconstructs the move history from a list of ABA-pro strings.
   *
   * <p>Parses the text generated by the save file and populates the undo stack.
   *
   * @param textMoves The list of moves parsed from the save file.
   */
  public History(List<String> textMoves) {
    GameLogger.debug("History: Reconstructing history from " + textMoves.size() + " lines.");
    for (String textMove : textMoves) {
      String cleanMove = textMove.trim();
      if (cleanMove.isEmpty()) {
        continue;
      }

      String mainPart = cleanMove;
      String capturePart = null;

      int openParen = cleanMove.indexOf('(');
      int closeParen = cleanMove.indexOf(')');

      if (openParen != -1 && closeParen != -1 && closeParen > openParen) {
        mainPart = cleanMove.substring(0, openParen).trim();
        capturePart = cleanMove.substring(openParen + 1, closeParen).trim();
      }

      String[] parts = mainPart.split("\\s+");

      if (parts.length >= 3) {
        char pieceChar = parts[0].charAt(0);
        int fromIdx =
            parts[1].equalsIgnoreCase("reloc")
                ? -1
                : CoordinateMapper.fromCoordinateString(parts[1]);
        int toIdx = CoordinateMapper.fromCoordinateString(parts[2]);

        Color moveColor = (pieceChar == 'O' || pieceChar == 'Q') ? Color.WHITE : Color.BLACK;
        PieceType type;
        if (pieceChar == 'Q') {
          type = PieceType.WHITE_QUEEN;
        } else if (pieceChar == 'q') {
          type = PieceType.BLACK_QUEEN;
        } else {
          type = (moveColor == Color.WHITE) ? PieceType.WHITE_PAWN : PieceType.BLACK_PAWN;
        }

        Move mainMove = new Move(fromIdx, toIdx, moveColor, type);
        List<Move> turnMoves = new ArrayList<>();
        turnMoves.add(mainMove);

        if (capturePart != null && !capturePart.isEmpty()) {
          String[] captures = capturePart.split(",");

          for (String capRaw : captures) {
            capRaw = capRaw.trim();

            if (!capRaw.isEmpty()) {
              String[] capParts = capRaw.split("\\s+");

              if (capParts.length >= 2) {
                char capPieceChar = capParts[0].charAt(0);
                int capIdx = CoordinateMapper.fromCoordinateString(capParts[1]);

                Color capColor =
                    (capPieceChar == 'O' || capPieceChar == 'Q') ? Color.WHITE : Color.BLACK;

                PieceType capType;
                if (capPieceChar == 'Q') {
                  capType = PieceType.WHITE_QUEEN;
                } else if (capPieceChar == 'q') {
                  capType = PieceType.BLACK_QUEEN;
                } else {
                  capType =
                      (moveColor == Color.WHITE) ? PieceType.WHITE_PAWN : PieceType.BLACK_PAWN;
                }

                Move capMove = new Move(capIdx, -1, capColor, capType);
                turnMoves.add(capMove);
              }
            }
          }
        }

        GameLogger.debug("History: Parsing move " + cleanMove);
        this.undoStack.push(new HistoryInformations(turnMoves, type, moveColor));
      }
    }
    GameLogger.info("History: Successfully loaded " + undoStack.size() + " turns from text.");
  }

  /**
   * Retrieves the most recent turn from the undo stack without removing it.
   *
   * @return The latest {@link HistoryInformations} on the undo stack.
   * @throws java.util.EmptyStackException if the undo stack is empty.
   */
  public HistoryInformations getHeadUndo() {
    return undoStack.peek();
  }

  /**
   * Retrieves the most recent turn from the redo stack without removing it.
   *
   * @return The latest {@link HistoryInformations} on the redo stack.
   * @throws java.util.EmptyStackException if the redo stack is empty.
   */
  public HistoryInformations getHeadRedo() {
    return redoStack.peek();
  }

  /**
   * Records a new turn in the history.
   *
   * <p>The turn is pushed onto the undo stack, and the redo stack is immediately cleared to ensure
   * history consistency.
   *
   * @param informations The {@link HistoryInformations} containing the move sequence to record.
   */
  public void add(HistoryInformations informations, String boardSignature) {
    undoStack.push(informations);
    signatureStack.push(boardSignature);

    configurationCounts.put(
        boardSignature, configurationCounts.getOrDefault(boardSignature, 0) + 1);
    if (!redoStack.isEmpty()) {
      GameLogger.debug("History: Clearing redo stack (new move played, branching timeline).");
      redoStack.clear();
      redoSignatureStack.clear();
    }
  }

  /**
   * Reverts the last recorded turn.
   *
   * <p>Pops the latest turn from the undo stack and transfers it to the redo stack.
   *
   * @return The {@link HistoryInformations} that was undone, or {@code null} if no moves are
   *     available to revert.
   */
  public HistoryInformations undo() {
    if (undoStack.isEmpty()) {
      GameLogger.debug("History: Undo requested but stack is empty.");
      return null;
    }
    if (!signatureStack.isEmpty()) {
      String lastSig = signatureStack.pop();
      redoSignatureStack.push(lastSig);

      int count = configurationCounts.getOrDefault(lastSig, 0);
      if (count <= 1) {
        configurationCounts.remove(lastSig);
      } else {
        configurationCounts.put(lastSig, count - 1);
      }
    }
    HistoryInformations informations = undoStack.pop();
    redoStack.push(informations);
    GameLogger.info(
        "History: Undone turn ("
            + informations.getColor()
            + "). UndoStack size: "
            + undoStack.size());
    return informations;
  }

  /**
   * Re-applies the most recently undone turn. *
   *
   * <p>Pops the turn from the redo stack and transfers it back to the undo stack.
   *
   * @return The {@link HistoryInformations} that was re-applied.
   * @throws java.util.EmptyStackException if the redo stack is empty.
   */
  public HistoryInformations redo() {
    if (redoStack.isEmpty()) {
      GameLogger.debug("History: Redo requested but stack is empty.");
      return null;
    }
    if (!redoSignatureStack.isEmpty()) {
      String sigToRestore = redoSignatureStack.pop();
      signatureStack.push(sigToRestore);
      configurationCounts.put(sigToRestore, configurationCounts.getOrDefault(sigToRestore, 0) + 1);
    }
    HistoryInformations informations = redoStack.pop();
    undoStack.push(informations);
    GameLogger.info(
        "History: Redone turn ("
            + informations.getColor()
            + "). UndoStack size: "
            + undoStack.size());
    return informations;
  }

  /**
   * Checks if there are any turns available to undo.
   *
   * @return {@code true} if the undo stack is empty, {@code false} otherwise.
   */
  public boolean isEmptyUndo() {
    return undoStack.isEmpty();
  }

  /**
   * Checks if there are any turns available to redo.
   *
   * @return {@code true} if the redo stack is empty, {@code false} otherwise.
   */
  public boolean isEmptyRedo() {
    return redoStack.isEmpty();
  }

  /**
   * Returns a list representation of the move history. This method converts the internal undo stack
   * into a list, reversing the order so that the moves are presented in chronological order (from
   * the first move to the most recent one).
   *
   * @return a {@link List} of {@link HistoryInformations} containing all performed moves in
   *     chronological order.
   */
  public List<HistoryInformations> toList() {
    return new ArrayList<>(undoStack);
  }

  /**
   * Converts the list of played turns into ABA-pro text format for saving.
   *
   * <p>Iterates through the undo stack chronologically and formats the primary move of each turn.
   *
   * @return A list of formatted strings, e.g., ["O c3 c5", "X e6 f5"]
   */
  public List<String> toTextList() {
    GameLogger.debug("History: Generating text list of moves for saving...");
    List<String> textMoves = new ArrayList<>();

    for (HistoryInformations info : this.undoStack) {
      if (info.getMoves().isEmpty()) {
        continue;
      }

      Move primaryMove = info.getMoves().get(0);

      String start = CoordinateMapper.toCoordinate(primaryMove.getFrom());
      String end = CoordinateMapper.toCoordinate(primaryMove.getDestination());

      char pieceChar;
      if (info.getColor() == Color.WHITE) {
        pieceChar = (primaryMove.getPieceType() == PieceType.WHITE_QUEEN) ? 'Q' : 'O';
      } else {
        pieceChar = (primaryMove.getPieceType() == PieceType.BLACK_QUEEN) ? 'q' : 'X';
      }

      StringBuilder moveBuilder = new StringBuilder();
      moveBuilder.append(pieceChar).append(" ").append(start).append(" ").append(end);

      if (info.getMoves().size() > 1) {
        moveBuilder.append(" (");

        for (int i = 1; i < info.getMoves().size(); i++) {
          Move capMove = info.getMoves().get(i);

          String capCoord = CoordinateMapper.toCoordinate(capMove.getFrom());

          char capChar;
          if (capMove.getColor() == Color.WHITE) {
            capChar = (capMove.getPieceType() == PieceType.WHITE_QUEEN) ? 'Q' : 'O';
          } else {
            capChar = (capMove.getPieceType() == PieceType.BLACK_QUEEN) ? 'q' : 'X';
          }

          moveBuilder.append(capChar).append(" ").append(capCoord);

          if (i < info.getMoves().size() - 1) {
            moveBuilder.append(", ");
          }
        }

        moveBuilder.append(")");
      }

      textMoves.add(moveBuilder.toString());
    }

    return textMoves;
  }

  public boolean isTripleRepetition(String currentSignature) {
    return configurationCounts.getOrDefault(currentSignature, 0) >= 3;
  }
}
