@startuml

skinparam actorStyle awesome
left to right direction
actor User

rectangle "CLI Interface" {
    (Launch the game)
    (Configure launch)
    (Choose display mode)
}

User --> (Launch the game)
User --> (Choose display mode)

(Launch the game) --> (Configure launch) : <<include>>
@enduml
