@startgantt
Language fr

saturday are closed
sunday are closed
'attention format : aaaa/jj/mm
Project starts the 2026/01/05
skinparam roundcorner 10

' dates de départ
2026/01/04 is colored in #ff0000
' date de fin (rendu)
2026/04/02 is colored in red

' oral pdp
2026/03/23 is colored in orange
2026/03/24 is colored in orange


<style>
ganttDiagram {
    fontName Arial
    fontSize 14
    task {
        BackgroundColor #EAEAEA
        BorderColor #555555
    }
    milestone {
        BackgroundColor #C62828
        FontColor white
        FontStyle bold
    }
}
</style>

[Semaine 0] as [s0] lasts 5 day
[Semaine 1] as [s1] starts at [s0]'s end and lasts 5 day
[Semaine 2] as [s2] starts at [s1]'s end and lasts 5 day
[Semaine 3] as [s3] starts at [s2]'s end and lasts 5 day
[Semaine 4] as [s4] starts at [s3]'s end and lasts 5 day
[Semaine 5] as [s5] starts at [s4]'s end and lasts 5 day
[Semaine 6] as [s6] starts at [s5]'s end and lasts 5 day
[Semaine 7] as [s7] starts at [s6]'s end and lasts 5 day
[Semaine 8] as [s8] starts at [s7]'s end and lasts 5 day
[Semaine 9] as [s9] starts at [s8]'s end and lasts 5 day
[Semaine 10] as [s10] starts at [s9]'s end and lasts 5 day
[Semaine 11] as [s11] starts at [s10]'s end and lasts 5 day
[Semaine 12] as [s12] starts at [s11]'s end and lasts 5 day

[s1] displays on same row as [s2]
[s2] displays on same row as [s3]
[s3] displays on same row as [s4]
[s4] displays on same row as [s5]
[s5] displays on same row as [s6]
[s6] displays on same row as [s7]
[s7] displays on same row as [s8]
[s8] displays on same row as [s9]
[s9] displays on same row as [s10]
[s10] displays on same row as [s11]
[s11] displays on same row as [s12]



[Explication du projet] as [begin] lasts 7 day
[pre-projet] as [preproj] starts at [begin]'s end and lasts 13 day
-- implementation --
[version 1 (base du jeu et CLI (GUI possible)] as [v1] starts at [preproj]'s end and lasts 10 day
[version 2 (GUI + IA)] as [v2] starts at [v1]'s end and lasts 10 days
[version 3 (IA + Network)] as [v3] starts at [v2]'s end and lasts 10 days
[finalisation] as [v4] starts at [v3]'s end and lasts 5 days
-- détails développement CLI --
[Théo : aide ponctuelle] as [tt2] starts at [preproj]'s end and lasts 10 days
[Félix : récupération des entrées pour traitement] as [ft3] starts at [preproj]'s end and lasts 13 days


-- détails développement réseau --

[Théo] as [theo] starts at [preproj]'s end and lasts 30 days

-- détails développement IA --

[Milan] as [milan] starts 2026/02/02 and lasts 30 days
[Félix: aide ponctuelle] as [ft2] starts at [preproj]'s end and lasts 30 days

-- détails développement GUI --

[Mathis] as [mathis] starts at [preproj]'s end and lasts 10 days
[Théo : aide ponctuelle] as [tt1] starts at [preproj]'s end and lasts 30 days

-- détails développement tests --

[Félix aide cohérence générale + performance] as [felix] starts at [preproj]'s end and lasts 35 days
[Milan : test IA] as [mit2] starts 2026/02/02 and lasts 30 days
[Théo : test réseau] as [tt3] starts at [v1]'s end and lasts 20 days
[Mathis : test ce qui est possible avec le GUI] as [mat1] starts at [preproj]'s end and lasts 30 days
[Lukas : test agon core] as [lt1] starts at [preproj]'s end and lasts 30 days

-- développement layer "technical" --

[implémentation peristance, langage et config] as [ft1] starts at [preproj]'s end and lasts 35 days

-- développement layer "agon core" --
[Lukas] as [lukas] starts at [preproj]'s end and lasts 20 days

-- légende --
[présentation du projet final] is colored in #orange/black
[fin de projet] is colored in #red/black
[impossible]  is colored in #ff000099/black
' assignation manuelle des couleurs
[theo] is colored in #cyan/black
[felix] is colored in #00cc1166/black
[milan] is colored in #pink/black 
[mathis] is colored in #FF96F9/black
[lukas] is colored in #9698FF/black

' tasks (cannot reuse same name or apply same colors to all)
' denomination : first letters of (2 if required): name + t 
' for first letter of "task" + number of task

' felix
[ft1] is colored in #00cc1166/black
[ft2] is colored in #00cc1166/black
[ft3] is colored in #00cc1166/black
' theo
[tt1] is colored in #cyan/black
[tt2] is colored in #cyan/black
[tt3] is colored in #cyan/black
' lukas
[lt1] is colored in #9698FF/black
' milan 
[mit2] is colored in #pink/black 
' mathis
[mat1] is colored in #pink/black 



@endgantt