@startuml
'https://plantuml.com/class-diagram

package commands {
interface CmdAction{
+boolean execute(MatchManager match);
   +createNew(String[] args):CmdAction
   + getDescription():String
   + getAutoCompleter():Completer
   + getName():String
   +getOptions(): Options
   + getHelp():String
}
    abstract class Cmd implements CmdAction{
    }

class AgonRegister{}
}
AgonRegister--CmdAction
@enduml